# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
pool:
  vmImage: 'windows-latest'

variables:
  - group: StageDeploy

stages:
- stage: Build
  displayName: 'Build & Test'
  jobs:
  - job: BuildAndTest
    displayName: 'Build & Test'

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK 6.0.x'
      inputs:
        version: '6.0.x'

    - task: NuGetAuthenticate@1
      displayName: 'Telerik Nuget Authentication'
      inputs:
        nuGetServiceConnections: 'TelerikWithNugetKey'

    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet Tool'

    - task: NuGetCommand@2
      displayName: 'Install NuGet Packages'
      inputs:
        restoreSolution: '**/*.sln'
        feedsToUse: 'config'
        nugetConfigPath: 'nuget.config'
        externalFeedCredentials: 'TelerikWithNugetKey'
  
    - task: VSBuild@1
      displayName: 'VS Build'
      inputs:
        solution: '**/*.sln'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)\\"'
        platform: 'Any CPU'
        configuration: $(BuildConfiguration)
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'

    - task: DotNetCoreCLI@2
      displayName: 'Running dotnet test'
      inputs:
        command: 'test'
        projects: |
          **/*Tests.csproj
