parameters:
  - name: webAppName
    default: 'menominee-api'

  - name: slot
    default: 'staging'

  - name: resourceGroup
    default: 'menominee'

  - name: artifactPath
    default: 'deploy-packages'

jobs:
  - deployment: DeployAPI
    displayName: Deploy API
    environment: Staging # Our CI/CD process ALWAYS deploys to the staging environment and slot
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: '${{ parameters.artifactPath }}'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: MenomineeDev
              RemoveAdditionalFilesFlag: true
              appType: 'webApp'
              WebAppName: '${{ parameters.webAppName }}'
              deployToSlotOrASE: true
              SlotName: '${{ parameters.slot }}'
              ResourceGroupName: '${{ parameters.resourceGroup }}' 
              packageForLinux: '$(Pipeline.Workspace)/${{ parameters.artifactPath }}/Menominee.Api.zip'
