// <auto-generated />
using System;
using MenomineePlayWASM.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MenomineePlayWASM.Shared.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Customers.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Inventory.InventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Core")
                        .HasColumnType("float");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Labor")
                        .HasColumnType("float");

                    b.Property<long?>("ManufacturerId")
                        .HasColumnType("bigint");

                    b.Property<double>("OnHand")
                        .HasColumnType("float");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PartType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<double>("Retail")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("InventoryItems", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Inventory.Manufacturer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MfrId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Prefix")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.CreditReturns.CreditReturn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CreditReturns");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.CreditReturns.CreditReturnItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Core")
                        .HasColumnType("float");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<long?>("CreditReturnId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MfrId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditReturnId");

                    b.ToTable("CreditReturnItems");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<long?>("VendorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorInvoices", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoiceItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Core")
                        .HasColumnType("float");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MfrId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("VendorInvoiceItems", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoicePayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<long?>("VendorInvoiceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VendorInvoiceId");

                    b.ToTable("VendorInvoicePayments", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoicePaymentMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PaymentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VendorInvoicePaymentMethods");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoiceTax", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("TaxId")
                        .HasColumnType("int");

                    b.Property<long?>("VendorInvoiceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VendorInvoiceId");

                    b.ToTable("VendorInvoiceTaxes", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.Vendors.Vendor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Vendors", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateInvoiced")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<long>("InvoiceNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("RepairOrderNumber")
                        .HasColumnType("bigint");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<string>("Vehicle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RepairOrders", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Core")
                        .HasColumnType("float");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCounterSale")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeclined")
                        .HasColumnType("bit");

                    b.Property<double>("LaborEach")
                        .HasColumnType("float");

                    b.Property<string>("ManufacturerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("QuantitySold")
                        .HasColumnType("float");

                    b.Property<long>("RepairOrderServiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("SaleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SaleType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderServiceId");

                    b.ToTable("RepairOrderItems", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderItemTax", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("LaborTax")
                        .HasColumnType("float");

                    b.Property<double>("LaborTaxRate")
                        .HasColumnType("float");

                    b.Property<double>("PartTax")
                        .HasColumnType("float");

                    b.Property<double>("PartTaxRate")
                        .HasColumnType("float");

                    b.Property<long>("RepairOrderItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<long>("TaxId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderItemId");

                    b.ToTable("RepairOrderItemTaxes", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("PaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("RepairOrderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderId");

                    b.ToTable("RepairOrderPayments", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderPurchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("RepairOrderItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint");

                    b.Property<string>("VendorInvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RepairOrderPurchases", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderSerialNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("RepairOrderItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderItemId");

                    b.ToTable("RepairOrderSerialNumbers", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCounterSale")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeclined")
                        .HasColumnType("bit");

                    b.Property<double>("LaborTotal")
                        .HasColumnType("float");

                    b.Property<double>("PartsTotal")
                        .HasColumnType("float");

                    b.Property<long>("RepairOrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("SaleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ShopSuppliesTotal")
                        .HasColumnType("float");

                    b.Property<double>("TaxTotal")
                        .HasColumnType("float");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderId");

                    b.ToTable("RepairOrderServices", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderServiceTax", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("LaborTax")
                        .HasColumnType("float");

                    b.Property<double>("LaborTaxRate")
                        .HasColumnType("float");

                    b.Property<double>("PartTax")
                        .HasColumnType("float");

                    b.Property<double>("PartTaxRate")
                        .HasColumnType("float");

                    b.Property<long>("RepairOrderServiceId")
                        .HasColumnType("bigint");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<long>("TaxId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderServiceId");

                    b.ToTable("RepairOrderServiceTaxes", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderTax", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("LaborTax")
                        .HasColumnType("float");

                    b.Property<double>("LaborTaxRate")
                        .HasColumnType("float");

                    b.Property<double>("PartTax")
                        .HasColumnType("float");

                    b.Property<double>("PartTaxRate")
                        .HasColumnType("float");

                    b.Property<long>("RepairOrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<long>("TaxId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderId");

                    b.ToTable("RepairOrderTaxes", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderTech", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("RepairOrderServiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("TechnicianId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderServiceId");

                    b.ToTable("RepairOrderTechs", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderWarranty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NewWarranty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OriginalInvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalWarranty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<long>("RepairOrderItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("RepairOrderItemId");

                    b.ToTable("RepairOrderWarranties", "dbo");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Inventory.InventoryItem", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.Inventory.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.CreditReturns.CreditReturnItem", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.Payables.CreditReturns.CreditReturn", null)
                        .WithMany("LineItems")
                        .HasForeignKey("CreditReturnId");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoice", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.Payables.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoiceItem", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoicePayment", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoice", null)
                        .WithMany("Payments")
                        .HasForeignKey("VendorInvoiceId");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoiceTax", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoice", null)
                        .WithMany("Taxes")
                        .HasForeignKey("VendorInvoiceId");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderItem", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderService", null)
                        .WithMany("Items")
                        .HasForeignKey("RepairOrderServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderItemTax", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderItem", null)
                        .WithMany("Taxes")
                        .HasForeignKey("RepairOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderPayment", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrder", null)
                        .WithMany("Payments")
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderSerialNumber", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderItem", null)
                        .WithMany("SerialNumbers")
                        .HasForeignKey("RepairOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderService", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrder", null)
                        .WithMany("Services")
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderServiceTax", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderService", null)
                        .WithMany("Taxes")
                        .HasForeignKey("RepairOrderServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderTax", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrder", null)
                        .WithMany("Taxes")
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderTech", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderService", null)
                        .WithMany("Techs")
                        .HasForeignKey("RepairOrderServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderWarranty", b =>
                {
                    b.HasOne("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderItem", null)
                        .WithMany("Warranties")
                        .HasForeignKey("RepairOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.CreditReturns.CreditReturn", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.Payables.Invoices.VendorInvoice", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Payments");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrder", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Services");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderItem", b =>
                {
                    b.Navigation("SerialNumbers");

                    b.Navigation("Taxes");

                    b.Navigation("Warranties");
                });

            modelBuilder.Entity("MenomineePlayWASM.Shared.Entities.RepairOrders.RepairOrderService", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Taxes");

                    b.Navigation("Techs");
                });
#pragma warning restore 612, 618
        }
    }
}
